// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeiligProgrammerenBlog.Models;

namespace VeiligProgrammerenBlog.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Auteur", b =>
                {
                    b.Property<int>("AuteurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Aanmelddatum")
                        .HasColumnType("datetime2");

                    b.HasKey("AuteurID");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Afbeelding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<string>("Beeld")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inhoud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LaatsteUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Plaatsingsdatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.HasIndex("AuteurId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Commentaar", b =>
                {
                    b.Property<int>("CommentaarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AantalRespects")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BlogId1")
                        .HasColumnType("int");

                    b.Property<string>("CommentaarInhoud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeplaatstDoor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaatsingsDatum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentaarID");

                    b.HasIndex("BlogId1");

                    b.ToTable("Commentaar");
                });

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Blog", b =>
                {
                    b.HasOne("VeiligProgrammerenBlog.Models.Auteur", "Auteur")
                        .WithMany()
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");
                });

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Commentaar", b =>
                {
                    b.HasOne("VeiligProgrammerenBlog.Models.Blog", "Blog")
                        .WithMany("Commentaar")
                        .HasForeignKey("BlogId1");

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("VeiligProgrammerenBlog.Models.Blog", b =>
                {
                    b.Navigation("Commentaar");
                });
#pragma warning restore 612, 618
        }
    }
}
